# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-25 12:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngagent', models.BinaryField()),
                ('ngagent_id', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CookieId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_uuid', models.CharField(default='', max_length=200)),
                ('user_agent_uuid', models.CharField(default='', max_length=200)),
                ('interaction_counter', models.IntegerField(default=0)),
                ('max_interaction', models.IntegerField(default=50)),
                ('exit_value', models.FloatField(default=0)),
                ('last_role', models.CharField(default='', max_length=200)),
                ('last_bool_succ', models.BooleanField(default=False)),
                ('last_nb_skipped', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PastInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.IntegerField()),
                ('meaning_h', models.IntegerField()),
                ('word', models.CharField(max_length=20)),
                ('bool_succ', models.IntegerField()),
                ('time_id', models.IntegerField()),
                ('role', models.CharField(max_length=20)),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ng.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ng.Experiment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='XpConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_config', models.CharField(max_length=2000, unique=True)),
                ('xp_cfg_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='last_mh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_mh', to='ng.Meaning'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='last_ms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_ms', to='ng.Meaning'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='last_w',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_w', to='ng.Word'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='meanings',
            field=models.ManyToManyField(related_name='meanings', to='ng.Meaning'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiment',
            name='words',
            field=models.ManyToManyField(related_name='words', to='ng.Word'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='xp_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ng.XpConfig'),
        ),
        migrations.AddField(
            model_name='agent',
            name='xp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ng.Experiment'),
        ),
    ]
