# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-29 11:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(default='fr', max_length=3)),
                ('tuto_played', models.BooleanField(default=False)),
                ('nbr_played', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cookieid',
            name='users',
            field=models.ManyToManyField(related_name='users', to='ng.UserNG'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ng.UserNG'),
        ),
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ng.UserNG'),
        ),
    ]
