# Generated by Django 2.0.7 on 2018-07-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userng',
            name='q1',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='userng',
            name='q2',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='userng',
            name='q3',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='userng',
            name='q4',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='userng',
            name='q5',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userng',
            name='q_filled',
            field=models.NullBooleanField(default=None),
        ),
    ]
