# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-29 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ng', '0003_auto_20180629_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userng',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserNG',
        ),
    ]
