# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-04 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('ng', '0004_auto_20180629_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNG',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lang', models.CharField(default='fr', max_length=3)),
                ('code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tuto_played', models.BooleanField(default=False)),
                ('nbr_played', models.IntegerField(default=0)),
            ],
        ),
    ]
