# Generated by Django 2.0.7 on 2018-07-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ng', '0004_auto_20180723_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userng',
            name='q1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userng',
            name='q2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userng',
            name='q3',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userng',
            name='q4',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
