# Generated by Django 2.0.7 on 2018-07-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ng', '0006_auto_20180723_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userng',
            name='q1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userng',
            name='q2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userng',
            name='q3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userng',
            name='q4',
            field=models.BooleanField(default=False),
        ),
    ]
