# Generated by Django 2.0.7 on 2018-07-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ng', '0007_auto_20180723_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='before_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='xp_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='userng',
            name='q_seen',
            field=models.BooleanField(default=False),
        ),
    ]
