# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-09 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ng', '0008_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastinteraction',
            name='meaning',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pastinteraction',
            name='meaning_h',
            field=models.CharField(max_length=20),
        ),
    ]
